<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>ssh-assistant-for-1password</ToolCommandName>
        <PackageOutputPath>./bin/nupkg</PackageOutputPath>

        <!-- Nuget package -->
        <PackageId>ssh-assistant-for-1password</PackageId>
        <Version>1.0.1</Version>
        <Description>SSH assistant for 1Password</Description>
        <PackageTags>ssh, git, 1password, ssh agent, 1password cli</PackageTags>
        <Authors>beeradmoore</Authors>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageProjectUrl>https://github.com/beeradmoore/SSH-Assistant-for-1Password</PackageProjectUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>

    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Spectre.Console" Version="0.54.0" />
      <PackageReference Include="Spectre.Console.Cli" Version="0.53.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SSHAssistantFor1Password.Core\SSHAssistantFor1Password.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Include="..\..\LICENSE" Pack="true" PackagePath="\">
        <Link>LICENSE</Link>
      </None>
      <None Include="..\..\README.md" Pack="true" PackagePath="\">
        <Link>README.md</Link>
      </None>
    </ItemGroup>

</Project>
